### PR TITLE
Entity query fixes

### LINKED ISSUE #105: Improve query naming for federated sub-graph calls requesting `_entities`
Given a Federated Gateway, where a sub-graph service serves up individual libraries and defines a 'Library' type and other sub graph services extend 'Library' and serve up 'booksInStock' and 'magazinesInStock' respectively for each 'Library' ID they receive.

When a query to the federated server queries for 'booksInStock' or 'magazinesInStock' which results in a _entities style query.

```
// Federated query
query SubGraphs {
  libraries {
    branch
    booksInStock {
      isbn,
      title,
      author
    }
    magazinesInStock {
      issue,
      title
    }
  }
}
```

```
// Resulting sub-graph query to books service
// where $representations is an args array of Library ID's {id: <id>, __typeName: 'Library'}
query($representations:[_Any!]!) {
  _entities(representations:$representations) {
    ...on Library {
      booksInStock {
        isbn 
        title 
        author
      }
    }
  }
}
```

To allow customers to understand which exact item _entities represents, particularly in the future where we may not show deeper paths when multiple items are requested at the top level, we are considering adding the type, which we get in the selection set, to the path designation of a transaction.

Below are some potential options (but options are not necessarily limited to these).

The goal is to provide clarity to differentiate these while being at least relatively intuitive to customers (understanding the Enities are mapping to the type Library via ID).

1. `_entities.Library` || `_entities.Library.booksInStock`
2. `_entities<Library>` || `_entities<Library>.booksInStock`
3. `[Library]` || `[Library].booksInStock`
4. `_entities on Library` || `_entities on Library.booksInStock`

### PR DESCRIPTION
**Pull request by bizob2828**
## Proposed Release Notes
 * Improved transaction names that contain InlineFragments(federated sub-graph calls, and union types)

## Links
Closes #105 

## Details
You can look at the added tests for union types and changes to the sub graph entity queries.  The solution was to go with 2nd option from #106 `_entities<Library>.booksInStock`.

### CODE REVIEW

File: lib/create-plugin.js [hunk 1]
```diff
@@ -356,16 +370,24 @@ function getDeepestUniqueSelection(definition) {
...
-    // Inline fragments do not have a name.
-    selection.name && deepestPath.push(selection.name.value)
+    if (isNamedType(selection)) {
+      const lastItemIdx = deepestPath.length - 1
+      // add type to the last item in deepestPath array
+      // (i.e - `_entities<Human>`)
+      deepestPath[lastItemIdx] =
+        `${deepestPath[lastItemIdx]}<${selection.typeCondition.name.value}>`
+    } else {
+      // Inline fragments do not have a name.
```
Comment (bizob2828) [inline lib/create-plugin.js:388]: this comment is prob no longer applicable, thoughts?

Comment (carlo-808) [reply lib/create-plugin.js:388]: Yeah, I think we can remove comment and leave defensive check, `selection.name &&`

**Review by carlo-808 — COMMENTED** [review]
Code looks great! I think we should add a note about Union type / Inline fragment naming in the transactoins.md docs.

File: lib/create-plugin.js (hunk 1 above)
Comment (bizob2828) [reply lib/create-plugin.js:388]: I may just remove the comment. i worry there are other types that lack name

**Review by carlo-808 — APPROVED** [review]
Updated transaction naming to handle Union type and Inline Fragments. 👍
